# Generated by Django 4.0.2 on 2022-09-18 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 9, 18, 8, 5, 34, 216148, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
